name: weatherapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # HTTP requests
  http: ^0.13.6
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints and codegen tools
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
